config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :expenses


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'recover-password' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', :to => "static#index"
  get 'about', :to => "static#about"
  get 'help', :to => "static#help"
  get 'faqs', :to => "static#faqs"
  get 'leave-policies', :to => "leaves#policies"
  root :to => "static#index"

  devise_scope :user do
    get 'profile', :to => "users#profile"
    get 'edit-profile', :to => "users#edit_profile"

    # Chat functionality
    get 'private-chat-rooms', to: 'chat_rooms#index'
    resources :chat_rooms, only: [:new, :create, :show, :index]

    # get 'create-retro', to: 'retros#create_retro'
    # resources :retros, only: [:show]

    # Pointing poker
    resources :pointing_pokers, only: [:new, :create, :show, :index]

    # Retros
    resources :retros, only: [:new, :create, :show, :index]
  end
  resources :teams
  resources :users
  resources :inspirational_quotes


  # root :to => 'chat_rooms#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :participants, class_name: "User"
  has_many :messages, dependent: :destroy

  def add_participants users
    self.participants << users
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }


  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :pointing_poker


  after_create_commit { PointBroadcastJob.perform_later(self) }
  after_create_commit { update_pointing_poker_channel }


  private


  def update_pointing_poker_channel
    channel_user = PointingPokerChannel.find_by(
      user_id: self.user_id,
      pointing_poker_id: self.pointing_poker_id
    )

    channel_user.update!(points: self.point)
  end

end

app/models/pointing_poker.rb
class PointingPoker < ApplicationRecord
  has_many :points, dependent: :destroy
  has_many :pointing_poker_channels, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
end

app/models/retro.rb
class Retro < ApplicationRecord
  belongs_to :user

  has_many :retro_responses
end

app/models/retro_response.rb
class RetroResponse < ApplicationRecord
  belongs_to :user
  belongs_to :retro


  def save_user_response(user, retro_id)

  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/team.rb
class Team < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :name, presence: true
	has_many :members, class_name: "User", dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :team, optional: true
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :chat_rooms_participations, class_name: 'ChatRoom' # shows all chatrooms where user was intivited as participant
  has_many :pointing_pokers, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :retros, dependent: :destroy
  has_many :retro_responses, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :questions, dependent: :destroy
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions = Question.all
    end

    def new
        @question = Question.new
    end

    def create
        @question = current_user.questions.build(question_params)
        if @question.save
          redirect_to '/questions'
        else
          render 'new'
        end
    end

    def show
        @question = Question.find(params[:id])
        @answers = @question.answers
    end    

    private
    def question_params
        params.require(:question).permit(:text)
    end    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
	def getColor index
		x = index % 4
		arr = ["team-skyblue", "team-red", "team-blue", "team-green"]
		arr[x]
	end

	def getInitial str=""
		str[0].capitalize
  end		
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/questions/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-9 about-us">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-md-12 lead">
			  	Questions <a class="btn btn-success pull-right" href="/questions/new" role="button">Ask new question</a>
                <hr>
              </div>
            </div>
            <div class="row">
              <div class="col-md-8">
			  <p>
			  	<% @questions.each_with_index do |question, index|%>
					<p><%=index+1%>: <a href="/questions/<%=question.id%>"><%= question.text %></a></p>
				<%end%>
			  </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
	<div class="form-group">
		<label>Questions</label>
		<%= f.text_area :text, class: "form-control", placeholder: "text"%>
	</div>
	<button class="btn btn-primary" type="submit">Save</button>	
<% end %>

app/views/questions/show.html.erb
Q: <%= @question.text%>

<p>
  <h2>Answers</h2>
  <% @answers.each_with_index do |answer, index|%>
    <p>
      <%= index+1%>: <%= answer.text%>
      <br/>
      <small> Posted by: <%= answer.user.name%> on <%= answer.created_at%></small>
    </p>
  <%end%>
</p>
<p>
  <%= form_for :answer, url: answers_path, method: :post do |f| %>
    <div class="form-group">
      <label>Submit new answer:</label>
      <%= f.hidden_field :question_id, value: @question.id %>
      <%= f.text_area :text, class: "form-control", placeholder: "text"%>
    </div>
    <button class="btn btn-primary" type="submit">Save</button>	
  <% end %>
</p>