config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :expenses


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'recover-password' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', :to => "static#index"
  get 'about', :to => "static#about"
  get 'help', :to => "static#help"
  get 'faqs', :to => "static#faqs"
  get 'leave-policies', :to => "leaves#policies"
  root :to => "static#index"

  devise_scope :user do
    get 'profile', :to => "users#profile"
    get 'edit-profile', :to => "users#edit_profile"

    # Chat functionality
    get 'private-chat-rooms', to: 'chat_rooms#index'
    resources :chat_rooms, only: [:new, :create, :show, :index]

    # get 'create-retro', to: 'retros#create_retro'
    # resources :retros, only: [:show]

    # Pointing poker
    resources :pointing_pokers, only: [:new, :create, :show, :index]

    # Retros
    resources :retros, only: [:new, :create, :show, :index]
  end
  resources :teams
  resources :users
  resources :inspirational_quotes


  # root :to => 'chat_rooms#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :participants, class_name: "User"
  has_many :messages, dependent: :destroy

  def add_participants users
    self.participants << users
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }


  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :pointing_poker


  after_create_commit { PointBroadcastJob.perform_later(self) }
  after_create_commit { update_pointing_poker_channel }


  private


  def update_pointing_poker_channel
    channel_user = PointingPokerChannel.find_by(
      user_id: self.user_id,
      pointing_poker_id: self.pointing_poker_id
    )

    channel_user.update!(points: self.point)
  end

end

app/models/pointing_poker.rb
class PointingPoker < ApplicationRecord
  has_many :points, dependent: :destroy
  has_many :pointing_poker_channels, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
end

app/models/retro.rb
class Retro < ApplicationRecord
  belongs_to :user

  has_many :retro_responses
end

app/models/retro_response.rb
class RetroResponse < ApplicationRecord
  belongs_to :user
  belongs_to :retro


  def save_user_response(user, retro_id)

  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/team.rb
class Team < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :name, presence: true
	has_many :members, class_name: "User", dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :team, optional: true
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :chat_rooms_participations, class_name: 'ChatRoom' # shows all chatrooms where user was intivited as participant
  has_many :pointing_pokers, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :retros, dependent: :destroy
  has_many :retro_responses, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :questions, dependent: :destroy
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      redirect_to @chat_room
    else
      render 'new'
    end
  end

  def show
    @current_user = current_user
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
	def getColor index
		x = index % 4
		arr = ["team-skyblue", "team-red", "team-blue", "team-green"]
		arr[x]
	end

	def getInitial str=""
		str[0].capitalize
  end		
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<%= form_for @chat_room do |f| %>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 lead">
                    Add chat room
                    <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                    <div class="form-group">
                        <%= f.label :title %>
                        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <%= f.submit "Add!", class: 'btn btn-primary' %>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
<% end %>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 lead">
              Join existing session
              <hr>
            </div>
          </div>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <br>
                <div class="input-group">
                  <input id="session-id" placeholder="Session ID" class="form-control" type="text"/>
                  <div class="input-group-append">
                    <button id="join-session" class="btn btn-primary" type="button">Join a session</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chat_rooms/show.html.erb
<div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 lead">
              <%= @chat_room.title %>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>" class="chat-box">
      <div class="row">
          <div class="col-md-8">
          <%= render @chat_room.messages %>
          </div>
      </div>
    </div>

<%= form_for @message, url: '#' do |f| %>
<div class="row">
  <div class="col-md-8">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>
      <small class="text-muted">From 2 to 1000 characters</small>
    </div>

  <%= f.submit "Post", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>